// Generated by CoffeeScript 1.9.3
(function() {
  var COOKIE_NAME, TRACK_URL, get_cookie, get_or_set_cookie, get_uuid, send_data, set_cookie;

  TRACK_URL = 'http://localhost:8001/golang.gif';

  COOKIE_NAME = '__goanalytics';

  get_uuid = function() {
    var d;
    d = (new Date).getTime();
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      var r;
      r = (d + Math.random() * 16) % 16 | 0;
      d = Math.floor(d / 16);
      return (c === 'x' ? r : r & 0x3 | 0x8).toString(16);
    });
  };

  get_cookie = function(c_name) {
    var c_end, c_start;
    if (document.cookie.length > 0) {
      c_start = document.cookie.indexOf(c_name + '=');
      if (c_start !== -1) {
        c_start = c_start + c_name.length + 1;
        c_end = document.cookie.indexOf(';', c_start);
        if (c_end === -1) {
          c_end = document.cookie.length;
        }
        return unescape(document.cookie.substring(c_start, c_end));
      }
    }
    return '';
  };

  set_cookie = function(c_name, value) {
    return document.cookie = c_name + '=' + escape(value);
  };

  get_or_set_cookie = function(c_name) {
    var uuid;
    uuid = get_cookie(c_name);
    if (!uuid) {
      uuid = get_uuid();
      set_cookie(c_name, uuid);
    }
    return uuid;
  };

  send_data = function() {
    var image, k, params, quary_string, src;
    params = {
      id: get_uuid(),
      cookieid: get_or_set_cookie(COOKIE_NAME),
      referer: encodeURIComponent(document.referrer),
      width: window.screen.width,
      height: window.screen.height,
      color: window.screen.colorDepth,
      title: encodeURIComponent(document.title),
      lang: navigator.browserLanguage ? navigator.browserLanguage : navigator.language
    };
    console.log(params);
    quary_string = '';
    for (k in params) {
      quary_string += '&' + k + '=' + params[k];
    }
    src = TRACK_URL + '?' + quary_string.slice(1, quary_string.length);
    image = new Image(1, 1);
    return image.src = src;
  };

  send_data();

}).call(this);
